# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'JTPromiseKit', :path => '../'

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'JTPromiseKit', :path => '../'
  end

  target 'ExampleUITests' do
    # Pods for testing
  end

end
