# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'JTPromiseExample' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for JTPromiseExample

  pod 'JTPromise', :path => '../'

  target 'JTPromiseExampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'JTPromise', :path => '../'
  end

  target 'JTPromiseExampleUITests' do
    # Pods for testing
  end

end
